### ISSUE TITLE
Runtime error if package.json does not contain a field "dependencies"

### ISSUE THREAD

**Issue by knopki** [roxiness/spank#2]
Failed on project with dev-dependencies only:

```shell
➜ spank
⠋ Looking for matching config(node:21433) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at getFrameworkConfig (/home/sk/dev/<cut>/node_modules/spank/getConfig.js:23:12)
    at Object.getConfig (/home/sk/dev/<cut>/node_modules/spank/getConfig.js:11:35)
    at cli (/home/sk/dev/<cut>/node_modules/spank/cli.js:8:51)
    at Object.<anonymous> (/home/sk/dev/<cut>/node_modules/spank/cli.js:29:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
(node:21433) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:21433) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠙ Looking for matching config⏎                                                                >
```

**Comment by jakobrosenberg** [comment]
Thanks @knopki. Off to bed now, but will have a look in the morning. 🙂
